added new data model
scout-tools/anmelde-tool pull request #17
Opened 2020-12-19 20:49 UTC by RobertBagdahn

2020-12-19 21:13 UTC, dhillebrand commented on backend/basic/migrations/0001_initial.py
> +            name='MeetHabit',
MeetHabit = MeatHabit!

2020-12-19 21:29 UTC, dhillebrand requested changes
Bitte die Rechtsschreibfehler korrigieren bevor wir in den Main mergen, sonst bekommen wir die nicht mehr raus.

2020-12-19 21:29 UTC, dhillebrand commented on .vscode/settings.json
> +{
Hier ist ne vscode Datei mit im Git.
@RobertBagdahn

2020-12-19 21:29 UTC, dhillebrand commented on frontend/src/store/index.js
> +    herarchy: [],
herarchy = hierarchy! @RobertBagdahn

2020-12-19 21:29 UTC, dhillebrand commented on frontend/src/views/registration/Main.vue
> +      // this.messages.forEach((value) => console.log(value));
Kommentar entfernen, da Merge in den Master @RobertBagdahn

2020-12-19 21:29 UTC, dhillebrand commented on frontend/src/views/settings/user/Main.vue
> +      // this.messages.forEach((value) => console.log(value));
Kommentar in Main merge @RobertBagdahn

2020-12-19 21:29 UTC, dhillebrand commented on frontend/src/views/settings/user/form/PickStamm.vue
> +      // if (this.propId && this.propId === this.active[0]) {
Kommentar in Main merge

2020-12-19 21:29 UTC, dhillebrand commented on frontend/src/views/settings/user/form/PickStamm.vue
> +          // You'll want to replace this with a more efficient search
Willst du das TODO absichtlich drinnen lassen für irgendwann mal? @RobertBagdahn

2020-12-19 21:29 UTC, dhillebrand commented on backend/basic/migrations/0001_initial.py
> +            name='MeetHabit',
MeetHabit = MeatHabit (Rechtschreibfehler) @RobertBagdahn

2020-12-19 21:29 UTC, dhillebrand commented on backend/basic/migrations/0001_initial.py
>              name='ScoutHerarchy',
Herarchy = Hierarchy! Rechtsschreibfehler @RobertBagdahn

2020-12-19 23:26 UTC, dhillebrand approved these changes

2020-12-20 17:07 UTC, philip5 commented on backend/anmeldung_auth/serializers.py
>          token['user'] = user.username
scoutname as username is email

2020-12-20 17:29 UTC, philip5 commented on backend/anmeldung_auth/models.py
> +    scoutOrganisation = models.ForeignKey(
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/anmeldung_auth/views.py
> +from rest_framework import pagination, viewsets, mixins, generics, filters
check unused imports

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
> +    zipCode = models.CharField(max_length=5, blank=True)
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
> +    zipCode = models.ForeignKey(
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
> +    contactEmail = models.CharField(max_length=30, blank=True)
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
> +    contactPhone = models.CharField(max_length=30, blank=True)
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
> +    zipCode = models.ForeignKey(
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
>      ageGroups = models.ManyToManyField(AgeGroup, blank=True)
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
>      startTime = models.DateTimeField(
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
>      minParticipation = models.IntegerField(blank=True, null=True)
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
>      maxParticipation = models.IntegerField(blank=True, null=True)
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
> +    isPublic = models.BooleanField(default=0)
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
> +    isActive = models.BooleanField(default=0)
check naming convention

2020-12-20 17:29 UTC, philip5 commented on backend/basic/models.py
> +    numberLactose = models.IntegerField(blank=True, null=True)
check naming convention

2020-12-23 13:43 UTC, philip5 approved these changes

2020-12-23 13:43 UTC, merged